# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /example/api_executor
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /example/example1
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /example/opentelemetry
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /example/streamed_list_objects
    schedule:
      interval: daily
