/**
 * Go SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 * License: [Apache-2.0](https://github.com/openfga/go-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */

package openfga

import (
	"encoding/json"
)

// V1Difference struct for V1Difference
type V1Difference struct {
	Base     *Userset `json:"base,omitempty"`
	Subtract *Userset `json:"subtract,omitempty"`
}

// NewV1Difference instantiates a new V1Difference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1Difference() *V1Difference {
	this := V1Difference{}
	return &this
}

// NewV1DifferenceWithDefaults instantiates a new V1Difference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1DifferenceWithDefaults() *V1Difference {
	this := V1Difference{}
	return &this
}

// GetBase returns the Base field value if set, zero value otherwise.
func (o *V1Difference) GetBase() Userset {
	if o == nil || o.Base == nil {
		var ret Userset
		return ret
	}
	return *o.Base
}

// GetBaseOk returns a tuple with the Base field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1Difference) GetBaseOk() (*Userset, bool) {
	if o == nil || o.Base == nil {
		return nil, false
	}
	return o.Base, true
}

// HasBase returns a boolean if a field has been set.
func (o *V1Difference) HasBase() bool {
	if o != nil && o.Base != nil {
		return true
	}

	return false
}

// SetBase gets a reference to the given Userset and assigns it to the Base field.
func (o *V1Difference) SetBase(v Userset) {
	o.Base = &v
}

// GetSubtract returns the Subtract field value if set, zero value otherwise.
func (o *V1Difference) GetSubtract() Userset {
	if o == nil || o.Subtract == nil {
		var ret Userset
		return ret
	}
	return *o.Subtract
}

// GetSubtractOk returns a tuple with the Subtract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1Difference) GetSubtractOk() (*Userset, bool) {
	if o == nil || o.Subtract == nil {
		return nil, false
	}
	return o.Subtract, true
}

// HasSubtract returns a boolean if a field has been set.
func (o *V1Difference) HasSubtract() bool {
	if o != nil && o.Subtract != nil {
		return true
	}

	return false
}

// SetSubtract gets a reference to the given Userset and assigns it to the Subtract field.
func (o *V1Difference) SetSubtract(v Userset) {
	o.Subtract = &v
}

func (o V1Difference) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Base != nil {
		toSerialize["base"] = o.Base
	}
	if o.Subtract != nil {
		toSerialize["subtract"] = o.Subtract
	}
	return json.Marshal(toSerialize)
}

type NullableV1Difference struct {
	value *V1Difference
	isSet bool
}

func (v NullableV1Difference) Get() *V1Difference {
	return v.value
}

func (v *NullableV1Difference) Set(val *V1Difference) {
	v.value = val
	v.isSet = true
}

func (v NullableV1Difference) IsSet() bool {
	return v.isSet
}

func (v *NullableV1Difference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1Difference(val *V1Difference) *NullableV1Difference {
	return &NullableV1Difference{value: val, isSet: true}
}

func (v NullableV1Difference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1Difference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
