/**
 * Go SDK for OpenFGA
 *
 * API version: 0.1
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://discord.gg/8naAwJfWN6
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */

package openfga

import (
	"encoding/json"
)

// AuthenticationErrorMessageResponse struct for AuthenticationErrorMessageResponse
type AuthenticationErrorMessageResponse struct {
	Code    *AuthErrorCode `json:"code,omitempty"`
	Message *string        `json:"message,omitempty"`
}

// NewAuthenticationErrorMessageResponse instantiates a new AuthenticationErrorMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationErrorMessageResponse() *AuthenticationErrorMessageResponse {
	this := AuthenticationErrorMessageResponse{}
	var code AuthErrorCode = NO_AUTH_ERROR
	this.Code = &code
	return &this
}

// NewAuthenticationErrorMessageResponseWithDefaults instantiates a new AuthenticationErrorMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationErrorMessageResponseWithDefaults() *AuthenticationErrorMessageResponse {
	this := AuthenticationErrorMessageResponse{}
	var code AuthErrorCode = NO_AUTH_ERROR
	this.Code = &code
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AuthenticationErrorMessageResponse) GetCode() AuthErrorCode {
	if o == nil || o.Code == nil {
		var ret AuthErrorCode
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationErrorMessageResponse) GetCodeOk() (*AuthErrorCode, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AuthenticationErrorMessageResponse) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given AuthErrorCode and assigns it to the Code field.
func (o *AuthenticationErrorMessageResponse) SetCode(v AuthErrorCode) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AuthenticationErrorMessageResponse) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationErrorMessageResponse) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AuthenticationErrorMessageResponse) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AuthenticationErrorMessageResponse) SetMessage(v string) {
	o.Message = &v
}

func (o AuthenticationErrorMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableAuthenticationErrorMessageResponse struct {
	value *AuthenticationErrorMessageResponse
	isSet bool
}

func (v NullableAuthenticationErrorMessageResponse) Get() *AuthenticationErrorMessageResponse {
	return v.value
}

func (v *NullableAuthenticationErrorMessageResponse) Set(val *AuthenticationErrorMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationErrorMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationErrorMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationErrorMessageResponse(val *AuthenticationErrorMessageResponse) *NullableAuthenticationErrorMessageResponse {
	return &NullableAuthenticationErrorMessageResponse{value: val, isSet: true}
}

func (v NullableAuthenticationErrorMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationErrorMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
