name: 🐛 Report a bug
description: Have you found a bug or issue? Create a bug report for OpenFGA
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: markdown
    attributes:
      value: |
        **Please do not report security vulnerabilities here**. Use https://github.com/openfga/go-sdk/security/advisories/new or send us an email at security@openfga.dev instead.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have looked into the [README](https://github.com/openfga/go-sdk/blob/main/README.md) and have not found a suitable solution or answer.
          required: true
        - label: I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
          required: true
        - label: I have searched the [issues](https://github.com/openfga/go-sdk/issues) and have not found a suitable solution or answer.
          required: true
        - label: I have upgraded to the [latest version](https://github.com/openfga/go-sdk/releases/latest) of OpenFGA and the issue still persists.
          required: true
        - label: I have searched the [Slack community](https://openfga.dev/community) and have not found a suitable solution or answer.
          required: true
        - label: I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: Tell us about the behavior you expected to see.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Detail the steps taken to reproduce this error and, ideally, share a repo of a minimal reproducible example. State whether this issue can be reproduced consistently or if it is intermittent.
      placeholder: |
        1. Given...
        2. When...
        3. Then...
    validations:
      required: true

  - type: input
    id: environment-sdk-version
    attributes:
      label: OpenFGA SDK version
      description: The version of Go SDK for OpenFGA you're using.
    validations:
      required: true

  - type: input
    id: environment-openfga-version
    attributes:
      label: OpenFGA version
      description: The version of OpenFGA you're using.
    validations:
      required: true

  - type: input
    id: environment-sdk-config
    attributes:
      label: SDK Configuration
      description: How are you initializing the SDK (DO NOT SHARE ANY SECRETS)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Do you have any logs or traces that could help us debug the problem?
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any references to other issues, PRs, documentation or other links
    validations:
      required: false

