blank_issues_enabled: false
contact_links:
  - name: 📖 OpenFGA's Documentation
    url: https://openfga.dev/docs
    about: Check OpenFGA's documentation for an in-depth overview
  - name: 👽 Community
    url: https://openfga.dev/community
    about: Join OpenFGA's community on Slack and GitHub Discussions
  - name: 📝 RFCs
    url: https://github.com/openfga/rfcs
    about: Check existing RFCs to understand where the project is headed
  - name: 💬 Discussions
    url: https://github.com/orgs/openfga/discussions
    about: Start a discussion about your authorization needs or questions
