name: Claude Code PR Review

on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]

jobs:
  claude-review:
    uses: openfga/ai-pr-analyzer-gh-action/.github/workflows/claude-code-review.yml@main