name: PR Title Conventional Commit Check

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: PR Conventional Commit Validation
        uses: ytanikin/pr-conventional-commits@639145d78959c53c43112365837e3abd21ed67c1 # v1.5.2
        with:
          task_types: '["feat","fix","docs","test","refactor","ci","perf","chore","revert","release"]'
          add_label: 'false'

